name: drupal-react
recipe: drupal9
config:
  webroot: drupal
  php: "8.0"
  composer_version: "2.2.12"
  database: mysql
  xdebug: false
  drush: true
proxy:
  nodejs:
    - node.lndo.site:3000
services:
  appserver:
    run:
      - "cd /app/drupal && composer install"
      - "composer require 'drupal/devel:^5.0'"
  nodejs:
    type: node:16
    ssl: true
    run:
      - "cd /app/react-app && npm install"
    port:
      - 3000
    env_file:
      - "/app/react-app/.env"
    overrides:
      ports: [3000:3000]
tooling:
  php:
    service: appserver
    dir: /app/drupal
  composer:
    service: appserver
    dir: /app/drupal
  drush:
    service: appserver
    cmd: "/app/drupal/vendor/drush/drush/drush"
  start-react:
    service: nodejs
    cmd:
      - "cd /app/react-app && npm start"
  start-drupal:
    service: appserver
    cmd:
      - /app/drupal/vendor/drush/drush/drush si --db-url=mysql://drupal9:drupal9@database:3306/drupal9 --site-name=decoupled --account-pass=admin
      - /app/drupal/vendor/drush/drush/drush en devel
      - /app/drupal/vendor/drush/drush/drush en devel_generate
      - /app/drupal/vendor/drush/drush/drush en jsonapi
      - /app/drupal/vendor/drush/drush/drush devel-generate:content
  node:
    service: nodejs
    dir: /app/react-app
  npm:
    service: nodejs
    dir: /app/react-app
