name: drupal-react
recipe: drupal9
config:
  webroot: drupal
  php: "8.0"
  composer_version: "2.2.12"
  database: mysql
proxy:
  nodejs:
    - node.lndo.site:3000
services:
  appserver:
    build:
      - "cd /app/drupal && composer install"
  nodejs:
    type: node:16
    ssl: true
    build:
      - cd /app/react-app && npm install
    port:
      - 3000
    overrides:
      ports: [3000:3000]
tooling:
  start-react:
    service: nodejs
    cmd:
      - "cd /app/react-app && npm start"
  node:
    service: nodejs
  npm:
    service: nodejs